import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard Settings',
  description: 'Generated by create next app',
};

export default function Page() {
  return <h1>Hello, Dashboard Settings Page!</h1>;
}
